project:
  type: book
  output-dir: docs

book:
  title: "Computing Infrastructure"
  author: "Luis A. Cueva Parra"
  date: "06/12/2025"
  chapters:
    - index.qmd
    - Hardware.qmd
    - SystemSoftware.qmd
    - BasicAppSoftware.qmd
    - SpecializedAppSoftware.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt



